### ISSUE TITLE
Wrapping byte[] with Mat (without copying data)

### ISSUE THREAD

**Issue by b005t3r** [bytedeco/javacv#1307]
Is there a way to wrap a byte array into a new `Mat` instance **without** copying the array?

Currently I do it like so:
```java
new Mat(height, width, CV_8UC3, new BytePointer(bufferPixels), step);
```

but calling `new BytePointer(bufferPixels)` allocates memory and copies `bufferPixels` into this newly allocated buffer. I couldn't find anything which would simply wrap `bufferPixels` into a new `Mat` - it this even possible?

**Comment by saudet** [comment]
No, it's not possible. There is no way to pin memory allocated for Java arrays across JNI calls.
That's why they came up with direct NIO buffers, so try to use those instead!

**Comment by saudet** [comment]
Well, technically, we can do it with functions in C/C++, where everything happens in a single JNI call. But you would have to code in C/C++, it wouldn't work from Java, and the longer it takes your function to execute, the higher the chances that you will prevent the JVM from executing other threads in Java. Anyway, like I said, that's what direct NIO buffers where introduced for, so try to use them in your application instead of Java arrays.
