### ISSUE TITLE
Does this library contains turbojpeg?

### ISSUE THREAD

**Issue by Wicz3k** [bytedeco/javacv#1634]
If contains what I need to do to enable it.

**Comment by saudet** [comment]
Yes. What is the issue?

**Comment by Wicz3k** [comment]
I call this function with Mat 1280x720 and `imencode` function take average 15ms per call.
```java
    private BytePointer bytemat = new BytePointer();
    private void pushImage(Mat image) {
            imencode(".jpg", image, bytemat);
            byte[] bytes = bytemat.getStringBytes();
    }
```
I think this is quite much time. I've got i7-4720HQ 4 cores 8 threads 3.4GHz. 
Is it possible to disable it at runtime to test performance without turbojpeg?

**Comment by saudet** [comment]
You won't be able to decode JPEG files at all without libjpeg-turbo.

**Comment by Wicz3k** [comment]
Ok, I was think that there is more than one jpeg codec.

**Comment by saudet** [comment]
It looks like OpenCV can use libjpeg instead of libjpeg-turbo with the CMake build option `BUILD_JPEG_TURBO_DISABLE=ON`. You can give that a try and see what you get. Build instructions are here: https://github.com/bytedeco/javacpp-presets#build-instructions

You could also try to use some other library like FFmpeg to decode JPEG, which may be faster libjpeg-turbo.
