### ISSUE TITLE
1.3.1 - 1.3.3 memory deallocation behaviour

### ISSUE THREAD

**Issue by theceday** [bytedeco/javacv#800]
I am really a beginner with opencv.
However there is strange behaviour change between versions
Not sure this is a bug though. 

Mat contour = drawContour..

This is an actually unused variable and is drawed with actual image size. (not contour bounding box etc)
(image size 1600, 1200)

Same image, approx 6K contour. 

1.3.1 keeping memory size around 150-200MB
1.3.3 after allocating 14GB memory, it crashes.

and this is replicable, happens everytime.
(same JDK, debug mode, no optimization etc)

Calling deallocate fixes the issue.

I really dont know whats the issue and whats could be changed, since Java doesnt have any way to deallocate scope variables?

**Comment by theceday** [comment]
maybe escape analysis doesnt work somehow?

**Comment by saudet** [comment]
There have been issues fixed in 1.3.3 such as
https://github.com/bytedeco/javacpp-presets/issues/423 so yes the behavior
should be better now. If you're still having problems though, please
provide a code snippet to reproduce the issue easily. It's not possible for
me to fix what isn't broken! Thanks
